# Generated by Django 3.2 on 2022-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20220620_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
