# Generated by Django 3.2 on 2022-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_userfeed_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='next_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
